name: Mobile App Build and Firebase Distribution

# This workflow will be manually triggered from GitHub UI, or opened by a pull request
on:
    pull_request:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment to build for'
                required: true
                default: 'plus'
                type: choice
                options:
                    - app
                    - plus

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        timeout-minutes: 5  # Add timeout to prevent hung builds

        steps:
            - name: Set Environment Variables
              run: |
                  # Set default environment based on event type
                  if [ "${{ github.event_name }}" = "pull_request" ]; then
                    # Default environment for pull requests is "plus"
                    KIND=plus
                  else
                    # For workflow_dispatch, use the input parameter
                    KIND=${{ github.event.inputs.environment }}
                  fi

                  # Use the KIND variable to set all other variables
                  if [ "${KIND}" = "plus" ]; then
                    echo "CFG=plus" >> $GITHUB_ENV
                  else
                    echo "CFG=production" >> $GITHUB_ENV
                  fi

                  # Set branch name based on event type
                  echo "BRANCH=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV

            - name: Debug info
              run: |
                  echo "KIND=${{ env.KIND }}"
                  echo "CFG=${{ env.CFG }}"
                  echo "BRANCH=${{ env.BRANCH }}"
